[package]
name = "migrant"
version = "0.9.7"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple migration manager for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"
exclude = ["ci/", ".travis.yml", "migrant_lib/", "migrations/", "*.db"]

[dependencies]
clap = "2"
error-chain = "0.11"
migrant_lib = { version = "0.11.4", path = "migrant_lib/" }
self_update = { version = "0.4.0", optional = true }

[workspace]
members = [
    "migrant_lib",
]

[features]
default = []
sqlite = ["migrant_lib/sqlite"]
postgresql = ["migrant_lib/postgresql"]
update = ["self_update"]
