[package]
name = "migrant"
version = "0.9.2"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple migration manager for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"
exclude = ["ci/", ".travis.yml", "migrant_lib/", "migrations/", "*.db"]

[dependencies]
clap = "2"
migrant_lib = { version = "0.11.2", path = "migrant_lib/" }

[workspace]
members = [
    "migrant_lib",
]

[features]
default = []
sqlite = ["migrant_lib/sqlite"]
postgresql = ["migrant_lib/postgresql"]
