[package]
name = "migrant"
version = "0.10.4"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple migration manager for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
categories = ["command-line-utilities", "database", "development-tools"]
license = "MIT"
exclude = [
    "/ci/*",
    "/migrations/*",
    "/db/*",
    "Migrant.toml",
    ".travis.yml",
]

[dependencies]
clap = "2"
error-chain = "0.11"
migrant_lib = { version = "0.16" }
self_update = { version = "0.4", optional = true }

[features]
default = []
sqlite = ["migrant_lib/sqlite"]
postgresql = ["migrant_lib/postgresql"]
update = ["self_update"]
