[package]
name = "migrant"
version = "0.11.1"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Database migration management for postgres, sqlite, mysql"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "postgres", "sqlite", "mysql"]
categories = ["command-line-utilities", "database", "development-tools"]
license = "MIT"
exclude = [
    "/ci/*",
    "/migrations/*",
    "/db/*",
    "Migrant.toml",
    ".travis.yml",
]

[dependencies]
clap = "2"
error-chain = "0.11"
migrant_lib = { version = "0.17" }
self_update = { version = "0.4", optional = true }

[features]
default = []
sqlite = ["migrant_lib/d-sqlite"]
postgres = ["migrant_lib/d-postgres"]
mysql = ["migrant_lib/d-mysql"]
update = ["self_update"]
