[package]
name = "migrant"
version = "0.2.2"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple migration manager for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"

[dependencies]
clap = "2.19.*"
rpassword = "0.3"
rustc-serialize = "0.3"
chrono = "0.2"
walkdir = "1"
error-chain = "0.7"

