[package]
name = "migrant"
version = "0.7.0"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple migration manager for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"

[dependencies]
clap = "2.19.*"
migrant_lib = { version = "0.7", path = "migrant_lib/" }

[features]
default = ["sqlite", "postgresql"]
sqlite = ["migrant_lib/sqlite"]
postgresql = ["migrant_lib/postgresql"]
