[package]
name = "migrant"
version = "0.4.0"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple migration manager for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"

[dependencies]
lazy_static = "0.2"
regex = "0.2"
clap = "2.19.*"
rpassword = "0.3"
chrono = "0.2"
walkdir = "1"
toml = "0.3"
serde = "0.9"
serde_derive = "0.9"
