[package]
name = "migrant"
version = "0.1.0"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple Postgres migration manager"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["sql", "migration", "postgres"]
license = "MIT"

[dependencies]
clap = "2.19.*"
rpassword = "0.3"
rustc-serialize = "0.3"
chrono = "0.2"
walkdir = "1"
error-chain = "0.7"

