[package]
name = "migrant_lib"
version = "0.8.0"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple database migration library for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"
workspace = ".."

exclude = [
    "db/*",
    "migrations/*",
]

[dependencies]
chrono = "0.3"
lazy_static = "0.2"
regex = "0.2"
rpassword = "0.4"
walkdir = "1"
serde = "1"
serde_derive = "1"
toml = "0.4"
postgres = {version = "0.14", optional = true}
rusqlite = {version = "0.12", optional = true, features = ["bundled"] }

[features]
default = ["sqlite", "postgresql"]
sqlite = ["rusqlite"]
postgresql = ["postgres"]
