[package]
name = "migrant_lib"
version = "0.11.4"
authors = ["James Kominick <james.kominick@gmail.com>"]
description = "Simple database migration library for postgres, sqlite"
repository = "https://github.com/jaemk/migrant"
keywords = ["database", "migration", "sql", "postgres", "sqlite"]
license = "MIT"
workspace = ".."

exclude = [
    "db/*",
    "migrations/*",
]

[dependencies]
error-chain = "0.11"
chrono = "0.4"
lazy_static = "0.2"
regex = "0.2"
walkdir = "1"
serde = "1"
serde_derive = "1"
toml = "0.4"
percent-encoding = "1"
url = "1"
postgres = {version = "0.15", optional = true}
rusqlite = {version = "0.12", optional = true, features = ["bundled"] }

[features]
default = []
sqlite = ["rusqlite"]
postgresql = ["postgres"]
